Build for android natively
randombenj/yelims pull request #2
Opened 2018-09-18 20:16 UTC by randombenj

Adds the `app/android` directory which enables to build an `.apk` file.

2018-09-19 06:24 UTC, eddex commented
do the changes in the [app/.babelrc](https://github.com/randombenj/yelims/pull/2/commits/75ca383c0e038eaccdb5e3599613282b4c8ddedc#diff-f2747bbc6b50e5a7acd1e710bac98340) file disable the live preview with expo?

2018-09-19 06:25 UTC, randombenj commented
Good point have to test it ...

2018-09-19 06:57 UTC, timofurrer commented
What would we have to do to also support iOS?

2018-09-19 07:25 UTC, eddex commented
> What would we have to do to also support iOS?

Buy a Mac, buy an iPhone, get an Apple developer account.. and then figure out how to do it :^)

2018-09-21 17:09 UTC, fliiiix reviewed
ich hoffe ich komm am Wochenende mal dazu das zu probieren

2018-09-21 17:09 UTC, fliiiix commented on app/android/app/src/main/AndroidManifest.xml
> +    package="com.yelims">
this is not ok :D

2018-09-24 11:07 UTC, fliiiix requested changes
npm start doesn't work

2021-09-22 11:34 UTC, closed without merging